### ISSUE TITLE
Tracking: Remove On Demand Run

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3029]
### Description
- [x] Add additional logging to measure runtime of each test and suite
- [x] File issues for feature teams to remove or convert MSTest tests to xunit
- [x] File issues for feature teams to Move on demand tests taking  < 1 second into the check-in tests
- [x] File issues for feature teams to remove or improve the runtime of remaining tests
- [ ] Send partner notifications for issues, set deadline,  and follow up until on demand run has no tests

**Comment by cormacpayne** [comment]
@markcowl created issues for teams that have on-demand tests that need to be moved to check-in. 

`Add additional logging to measure runtime of each test and suite`
- Currently we can see the runtime of each test. What additional logging are we looking to add?

**Comment by maddieclayton** [comment]
All tests are moved except for flaky tests and mstests.  MSTests will be moved into CI when ServiceManagement is split into a separate repo, and issues for the flaky tests will be opened against the correct teams:

Batch
Compute (strategies)
Resources: Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests.RaPropertiesValidation

**Comment by maddieclayton** [comment]
For documentation, these skipped tests were moved from on demand into CI, so we don't know how much time they take:

Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerDisasterRecoveryConfigurationTests.TestServerDisasterRecoveryConfiguration

Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests.TestAEMExtensionAdvancedWindows
Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests.TestAEMExtensionAdvancedWindowsMD
Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests.TestAEMExtensionBasicWindowsWAD

Microsoft.Azure.Commands.Resources.Test.Models.ResourceClientTests.SerializeHashtableProperlyHandlesAllDataTypes
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ActiveDirectoryTests.TestGetADUserWithFPOUPN
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests.TestNestedDeploymentFromTemplateFile
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests.TestNewDeploymentWithComplexPramaters
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests.TestNewDeploymentWithKeyVaultReference
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests.TestSaveDeploymentTemplateFile
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.DeploymentTests.TestValidateDeployment
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.MoveResourceTest.TestMoveAzureResource
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceGroupTests.TestAzureTagsEndToEnd
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceGroupTests.TestGetNonExistingResourceGroupWithDebugStream
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.ResourceGroupTests.TestRemoveDeployment
Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests.RaUserPermissions

Microsoft.WindowsAzure.Commands.Test.CloudService.Development.Scaffolding.AddAzureWebRoleTests.AddAzureWebRoleWithTemplateFolder
Microsoft.WindowsAzure.Commands.Test.CloudService.Development.Scaffolding.AddAzureWorkerRoleTests.AddAzureWorkerRoleWithTemplateFolder
Microsoft.WindowsAzure.Commands.Test.CloudService.Development.Scaffolding.NewAzureRoleTemplateTests.NewAzureRoleTemplateWithRunningOutsideDefaultDirectory
Microsoft.WindowsAzure.Commands.Test.CloudService.Utilities.CloudServiceClientTests.TestCreateStorageServiceWithPublish
Microsoft.WindowsAzure.Commands.Test.CloudService.Utilities.CloudServiceClientTests.TestPublishNewCloudService
Microsoft.WindowsAzure.Commands.Test.CloudService.Utilities.CloudServiceClientTests.TestPublishWithCurrentStorageAccount
Microsoft.WindowsAzure.Commands.Test.CloudService.Utilities.CloudServiceClientTests.TestPublishWithDefaultLocation
Microsoft.WindowsAzure.Commands.Test.CloudService.Utilities.CloudServiceClientTests.TestUpgradeCloudService
Microsoft.WindowsAzure.Commands.Test.Profile.GetAzurePublishSettingsFileTests.GetsPublishSettingsFileUrl
Microsoft.WindowsAzure.Commands.Test.Websites.ShowAzurePortalTests.ProcessGetAzurePublishSettingsTest
Microsoft.WindowsAzure.Commands.Test.Websites.ShowAzureWebsiteTests.ProcessShowWebsiteTest
