### ISSUE TITLE
Update NetStandard PowerShell to use ~/.azure directory by default for context persistence

### ISSUE THREAD

**Issue by jianyunt** [Azure/azure-powershell#6000]
Thank you @alexandair for reporting this issue.On Linux bash cloudshell, we are seeing **Windows\Azure\Powershell** folder containing info for whether enable or disable datacollection.  I am seeing a few issues:
1) As AzureRM modules are supported on CoreCLR now, we install them on PowerShell core. Thus "Windows" word is not applicable on Linux. Suggestion: remove it.
2)  "Powershell": should be "Power**S**hell"?
3)  AzurePSDataCollectionProfile.json exists in different locations for different users on bash cloudshell and pwsh 

From Alex: On bash cloudshell,  

psconfeu@Azure:~$ dir
clouddrive  **Windows\Azure\Powershell**

It also repros by Danny too. The file exists under Home for Linux and Modules folder for Windows (I guess).
![image](https://user-images.githubusercontent.com/10171679/39020548-35e20438-43e2-11e8-9124-50931f5fcf88.png)

On my cloudshell, **Windows\Azure\Powershell** gets created under .config.

![image](https://user-images.githubusercontent.com/10171679/39020849-1caf6658-43e3-11e8-991b-5fa185cd4037.png)

### Script/Steps for Reproduction

- go to portal.azure.com portal
- click on cloudshell icon to launch cloudshell and select bash
- type pwsh
```powershell

```

### Module Version

![image](https://user-images.githubusercontent.com/10171679/39021099-3dc1f184-43e4-11e8-99c3-58060fef5d56.png)

### Environment Data

```powershell
PS Azure:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Linux 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Debug Output

It looks like `Windows Azure Powershell is defined in here 

https://github.com/Azure/azure-powershell/blob/8b467df53bf1b79144afb1250221ec7e6b3a8b44/src/Common/Commands.Common.Authentication/Properties/Resources.resx#L124

https://github.com/Azure/azure-powershell/blob/8b467df53bf1b79144afb1250221ec7e6b3a8b44/src/Common/Commands.Common.Authentication/Properties/Resources.resx#L124

This place is for errors logging:
https://github.com/Azure/azure-powershell/blob/7fd657a2e53f7b4f1571acb75bdee2a376c3094d/src/Common/Commands.Common/AzurePowerShell.cs#L45

**Comment by markcowl** [comment]
@jianyunt Thanks, plans are to move this directory (we are considering   .Azure as it is for CLI), but this is considered a low priority item at this point, as normally users do not need to worry about the directory.

**Comment by MiYanni** [comment]
I'll try to get this done as part of my repo refactoring efforts.

**Comment by markcowl** [comment]
### Task Description

- [ ] Update default directory to ~/.Azure
- [ ] Write conversion code to move any persisted context from the AppData\Roaming\Windows Azure PowerShell Directory
- [ ] Tests for conversion code

### Cost: 6

**Comment by markcowl** [comment]
Fixed
