### ISSUE TITLE
Track work for generated Dns cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#9370]
## Outstanding Issues

- [Name in body parameters should not be exposed](https://github.com/Azure/autorest.powershell/issues/324)
- [If-match (etag) not being generated](https://github.com/Azure/autorest.powershell/issues/339)
- Pattern for parent resources

### Dns

- [ ] ~~`Get-AzDnsRecordSet`~~
    - [ ] ~~Rename `-RelativeRecordSetName` to `-Name` and add alias back to original (blocked by issue https://github.com/Azure/autorest.powershell/issues/324)~~
    - [ ] ~~Variant to add `-Zone` parameter -- do we want to do this?~~
- [ ] ~~`Get-AzDnsResourceReference`~~
    - [ ] ~~Investigate if we should add `-TargetResourceId`~~
- [ ] ~~`Get-AzDnsZone`~~
- [ ] ~~`New-AzDnsRecordSet`~~
    - [ ] ~~Rename `-RelativeRecordSetName` to `-Name` and add alias back to original (blocked by issue https://github.com/Azure/autorest.powershell/issues/324)~~
    - [ ] ~~Variant to add `-Zone` parameter -- do we want to do this?~~
    - [ ] ~~Variant to add `-DnsRecords`~~
    - [ ] ~~Existing `-Overwrite` cannot currently be added (blocked by issue https://github.com/Azure/autorest.powershell/issues/339)~~
- [ ] ~~`New-AzDnsZone`~~
    - [ ] ~~Investigate if we should add `-RegistrationVirtualNetworkId` and `-ResolutionVirtualNetworkId`~~
- [ ] ~~`Remove-AzDnsRecordSet`~~
    - [ ] ~~Rename `-RelativeRecordSetName` to `-Name` and add alias back to original (blocked by issue https://github.com/Azure/autorest.powershell/issues/324)~~
    - [ ] ~~Variant to add `-Zone` parameter -- do we want to do this?~~
    - [ ] ~~Existing `-RecordSet` can be ignored since it's covered by `-InputObject`~~
    - [ ] ~~Existing `-Overwrite` cannot currently be added (blocked by issue https://github.com/Azure/autorest.powershell/issues/339)~~
- [ ] ~~`Remove-AzDnsZone`~~
    - [ ] ~~Existing `-Zone` can be ignored since it's covered by `-InputObject`~~
    - [ ] ~~Existing `-Overwrite` cannot currently be added (blocked by issue https://github.com/Azure/autorest.powershell/issues/339)~~
- [ ] ~~`Set-AzDnsRecordSet`~~
    - [ ] ~~Rename `-RelativeRecordSetName` to `-Name` and add alias back to original (blocked by issue https://github.com/Azure/autorest.powershell/issues/324)~~
    - [ ] ~~Existing `-RecordSet` can be ignored since it's covered by `-InputObject`~~
    - [ ] ~~Existing `-Overwrite` cannot currently be added (blocked by issue https://github.com/Azure/autorest.powershell/issues/339)~~
    - [ ] ~~Variant to add in intermittent properties needed for each of the record properties (_e.g._, `-ARecord`, `-AaaaRecord`, `-CaaRecord`, etc.)~~
- [ ] ~~`Set-AzDnsZone`~~
    - [ ] ~~Investigate if we should add `-RegistrationVirtualNetworkId` and `-ResolutionVirtualNetworkId`~~
    - [ ] ~~Existing `-Zone` can be ignored since it's covered by `-InputObject`~~
    - [ ] ~~Existing `-Overwrite` cannot currently be added (blocked by issue https://github.com/Azure/autorest.powershell/issues/339)~~
- [ ] ~~`Update-AzDnsRecordSet`~~
    - [ ] ~~Rename `-RelativeRecordSetName` to `-Name` and add alias back to original (blocked by issue https://github.com/Azure/autorest.powershell/issues/324)~~
    - [ ] ~~Variant to add in intermittent properties needed for each of the record properties (_e.g._, `-ARecord`, `-AaaaRecord`, `-CaaRecord`, etc.)~~
- [ ] ~~`Update-AzDnsZone`~~

### Not Generated

- [ ] ~~`Add-AzDnsRecordConfig`~~
    - [ ] ~~In-memory object cmdlet that shouldn't be needed anymore due to `Update-AzDnsRecordSet`~~
- [ ] ~~`New-AzDnsRecordConfig`~~
    - [ ] ~~In-memory object cmdlet that shouldn't be needed anymore due to `Update-AzDnsRecordSet`~~
- [ ] ~~`Remove-AzDnsRecordConfig`~~
    - [ ] ~~In-memory object cmdlet that shouldn't be needed anymore due to `Update-AzDnsRecordSet`~~

**Comment by MiYanni** [comment]
I ended up writing custom cmdlet surfaces for:
- `Get-AzDnsResourceReference`
- `New/Set/Update-AzDnsRecordSet`
- `New/Set-AzDnsZone`

These surfaces better match the intent of the resource/API. The swagger poorly defines what makes sense when making these resources. The ResourceReference one was a simple fix to flatten an array, which could be resolved by https://github.com/Azure/autorest.powershell/issues/467. However, without that change, it needed to be a customization.
